#! /bin/sh
getent passwd wwwrunner || useradd -mr wwwrunner
sudo -Hu wwwrunner sh -c 'mkdir ~/R'
sudo -Hu wwwrunner sh -c 'echo R_LIBS_USER=~/R > ~/.Renviron'
sudo -Hu wwwrunner Rscript -e "install.packages(pkgs=c('remotes'),lib='~/R')"
sudo -Hu wwwrunner Rscript -e "remotes::install_github(repo=c('tim-band/shinylight', 'pvermees/GeoplotR','pvermees/GeoplotRgui'),lib='~/R')"
/usr/local/sbin/updateGeoplotR.sh
/usr/local/sbin/geoplotrctl enable
/usr/local/sbin/geoplotrctl start
systemctl restart nginx
